const ACTION_CONFIG_SHARED_DEFAULTS = {
  textStyle: "阿拉伯数字 (1, 2, 3)",
  textMode: "默认模式 (+1)",
  textTemplate: "${number}",
  textTagPlayMode: "按顺序显示",
  textOpacity: 100,
  textFontFamily: "系统默认",
  textOutlineWidth: 0,
  comboEnabled: false,
  textOffsetX: 0,
  particleStyle: "点状粒子",
  particleColorMode: "跟随主题",
  particlePalette: ["#FBBF24", "#F59E0B", "#FDE68A", "#FCD34D", "#FEF3C7"],
  particleGravity: 0,
  particleWind: 0,
  particleBounce: 0,
  particleTrail: false,
  rippleStyle: "单环",
  rippleLineWidth: 2,
  rippleColor: "#F59E0B",
  soundBlendMode: "保持原音量",
  playbackRate: 100,
  soundDelay: 0,
  animationEnabled: false,
  animationStyle: "聚焦脉冲",
  animationDuration: 720,
  animationEasing: "缓出",
  animationScale: 100,
  animationOpacity: 100,
  animationOffsetX: 0,
  animationOffsetY: -10,
  animationColor: "#F59E0B",
  animationGlow: false,
  imageEnabled: false,
  imageDataUrl: "",
  imageDuration: 780,
  imageSize: 56,
  imageOpacity: 100,
  imageOffsetX: 0,
  imageOffsetY: -18,
  textGradient: false,
  textGradientStart: "#FBBF24",
  textGradientEnd: "#EC4899",
  cursorTrailEnabled: false,
  cursorTrailCount: 5,
  cursorTrailOpacity: 50,
  cursorGlowColor: "",
  comboWindowMs: 900,
  textDelay: 0,
  rippleDelay: 0,
  particleDelay: 0,
  animationDelay: 0,
  imageDelay: 0,
  particleMotionMode: "burst",
  orbitalCount: 6,
  orbitalRadius: 32,
  orbitalSpeed: 3,
};

function createActionConfig(overrides) {
  return {
    ...ACTION_CONFIG_SHARED_DEFAULTS,
    ...overrides,
    textTags: [...(overrides.textTags || [])],
  };
}

function cloneActionConfig(config) {
  return {
    ...config,
    textTags: [...(config.textTags || [])],
  };
}

const ACTION_CONFIG_PRESETS = {
  leftClick: createActionConfig({
    textKind: "数字飘字",
    textEnabled: true,
    textContent: "+1",
    textTags: ["功德 +1", "继续点击", "已触发"],
    textColor: "#B45309",
    textDuration: 1000,
    textEasing: "弹跳",
    textWeight: "加粗",
    textShadow: "柔和",
    comboEnabled: true,
    textOffsetY: -28,
    particle: true,
    particleCount: 22,
    particleSpread: 62,
    particleStyle: "火花",
    particleDirection: "四周扩散",
    particleDuration: 780,
    particleSize: 14,
    particleOpacity: 88,
    particleGravity: 8,
    particleBounce: 14,
    ripple: true,
    rippleSize: 72,
    rippleDuration: 860,
    rippleStyle: "回声环",
    rippleEasing: "缓出",
    rippleOpacity: 72,
    sound: true,
    fontSize: 24,
    volume: 72,
    soundFadeOut: 80,
    soundTriggerMode: "每次触发",
    shake: 48,
    cursorOverride: "木鱼（继承默认）",
    cursorSize: 48,
    cursorTrailEnabled: true,
    cursorTrailCount: 4,
    cursorTrailOpacity: 36,
    cursorGlowColor: "#F59E0B",
    imageEnabled: false,
    triggerTiming: "抬起时",
    triggerZone: "当前页面可点击区域",
    holdMs: 0,
    soundFile: "woodfish-soft.wav",
  }),
  rightClick: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "menu",
    textTags: ["展开菜单", "右键操作", "更多选项"],
    textColor: "#475569",
    textDuration: 820,
    textEasing: "缓出",
    textWeight: "中等",
    textShadow: "无",
    textOffsetY: -18,
    particle: true,
    particleCount: 14,
    particleSpread: 40,
    particleDirection: "四周扩散",
    particleDuration: 560,
    particleSize: 10,
    particleOpacity: 72,
    ripple: true,
    rippleSize: 50,
    rippleDuration: 560,
    rippleStyle: "双环",
    rippleEasing: "缓出",
    rippleOpacity: 62,
    sound: false,
    fontSize: 18,
    volume: 60,
    soundFadeOut: 40,
    soundTriggerMode: "节流播放",
    shake: 22,
    cursorOverride: "跟随当前状态",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "菜单弹出前",
    triggerZone: "右键菜单前",
    holdMs: 0,
    soundFile: "tick-light.wav",
  }),
  doubleClick: createActionConfig({
    textKind: "数字飘字",
    textStyle: "英文单词 (one, two, three)",
    textMode: "模板模式",
    textTemplate: "combo ${number}",
    textEnabled: true,
    textContent: "combo",
    textTags: ["双击完成", "连击命中", "combo"],
    textTagPlayMode: "随机显示",
    textColor: "#0F766E",
    textDuration: 1100,
    textEasing: "弹性",
    textWeight: "加粗",
    textOutlineWidth: 1,
    textShadow: "柔和",
    comboEnabled: true,
    textOffsetY: -30,
    particle: true,
    particleCount: 26,
    particleSpread: 74,
    particleStyle: "火花",
    particleDirection: "四周扩散",
    particleColorMode: "随机轻变化",
    particlePalette: ["#14B8A6", "#0F766E", "#5EEAD4", "#99F6E4", "#CCFBF1"],
    particleDuration: 980,
    particleSize: 16,
    particleOpacity: 96,
    ripple: true,
    rippleSize: 84,
    rippleDuration: 940,
    rippleStyle: "双环",
    rippleEasing: "弹性",
    rippleLineWidth: 3,
    rippleOpacity: 84,
    rippleColor: "#14B8A6",
    sound: true,
    fontSize: 24,
    volume: 80,
    playbackRate: 104,
    soundFadeOut: 90,
    soundTriggerMode: "连击叠加",
    soundBlendMode: "压低页面音频",
    shake: 52,
    cursorOverride: "木鱼（增强态）",
    cursorSize: 52,
    cursorTrailEnabled: true,
    cursorTrailCount: 5,
    cursorTrailOpacity: 42,
    cursorGlowColor: "#14B8A6",
    imageEnabled: false,
    triggerTiming: "第二次抬起后",
    triggerZone: "双击命中区域",
    holdMs: 320,
    soundFile: "woodfish-deep.wav",
  }),
  longPress: createActionConfig({
    textKind: "文本飘字",
    textStyle: "中文数字 (一, 二, 三)",
    textEnabled: false,
    textContent: "蓄",
    textTags: ["按住中", "蓄力完成", "松开触发"],
    textColor: "#7C3AED",
    textDuration: 900,
    textEasing: "缓入缓出",
    textOpacity: 94,
    textWeight: "中等",
    textShadow: "柔和",
    textOffsetY: -22,
    particle: true,
    particleCount: 16,
    particleSpread: 48,
    particleStyle: "碎屑粒子",
    particleDirection: "向上喷发",
    particlePalette: ["#A78BFA", "#7C3AED", "#C4B5FD", "#DDD6FE", "#EDE9FE"],
    particleDuration: 740,
    particleSize: 12,
    particleOpacity: 78,
    ripple: true,
    rippleSize: 62,
    rippleDuration: 780,
    rippleStyle: "柔和面波",
    rippleEasing: "缓入缓出",
    rippleOpacity: 56,
    rippleColor: "#A78BFA",
    sound: true,
    fontSize: 20,
    volume: 72,
    playbackRate: 92,
    soundDelay: 60,
    soundFadeOut: 120,
    soundTriggerMode: "每次触发",
    soundBlendMode: "压低页面音频",
    shake: 58,
    cursorOverride: "木鱼（按压态）",
    cursorSize: 50,
    imageEnabled: false,
    triggerTiming: "松开后触发",
    triggerZone: "按住后释放",
    holdMs: 560,
    soundFile: "woodfish-deep.wav",
  }),
  wheel: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "roll",
    textTags: ["向上滚动", "向下滚动", "继续滚动"],
    textTagPlayMode: "随机显示",
    textColor: "#0284C7",
    textDuration: 700,
    textEasing: "线性",
    textOpacity: 90,
    textWeight: "常规",
    textShadow: "无",
    textOffsetY: -14,
    particle: true,
    particleCount: 10,
    particleSpread: 36,
    particleDirection: "四周扩散",
    particleColorMode: "跟随飘字色",
    particleDuration: 460,
    particleSize: 10,
    particleOpacity: 72,
    ripple: true,
    rippleSize: 38,
    rippleDuration: 500,
    rippleStyle: "单环",
    rippleEasing: "线性",
    rippleLineWidth: 1,
    rippleOpacity: 46,
    rippleColor: "#0284C7",
    sound: false,
    fontSize: 16,
    volume: 40,
    playbackRate: 110,
    soundFadeOut: 30,
    soundTriggerMode: "节流播放",
    shake: 16,
    cursorOverride: "跟随当前状态",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "连续滚动中",
    triggerZone: "向上 / 向下滚轮",
    holdMs: 180,
    soundFile: "tick-light.wav",
  }),
  hover: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "hover",
    textTags: ["已聚焦", "经过目标", "可点击"],
    textTagPlayMode: "随机显示",
    textColor: "#475569",
    textDuration: 680,
    textEasing: "缓入缓出",
    textOpacity: 88,
    textWeight: "常规",
    textShadow: "无",
    textOffsetY: -12,
    particle: false,
    particleCount: 8,
    particleSpread: 24,
    particleDirection: "向上喷发",
    particleDuration: 420,
    particleSize: 8,
    particleOpacity: 60,
    ripple: true,
    rippleSize: 34,
    rippleDuration: 440,
    rippleStyle: "柔和面波",
    rippleEasing: "缓入缓出",
    rippleLineWidth: 1,
    rippleOpacity: 32,
    rippleColor: "#94A3B8",
    sound: false,
    fontSize: 16,
    volume: 0,
    soundFadeOut: 0,
    soundTriggerMode: "节流播放",
    shake: 0,
    cursorOverride: "切换到 pointer",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "停留后",
    triggerZone: "进入可交互元素",
    holdMs: 220,
    soundFile: "tick-light.wav",
  }),
};

const THEME_ACTION_OVERRIDES = {
  "mono-geo": {
    leftClick: {
      textKind: "数字飘字", textEnabled: true, textContent: "+1",
      textTags: ["+1", "+2", "+3"],
      textColor: "#1E293B", fontSize: 20, textWeight: "中等", textEasing: "线性", textShadow: "无",
      textFontFamily: "等宽字体", comboEnabled: true,
      particle: true, particleStyle: "方块", particleCount: 18, particleSpread: 56,
      particlePalette: ["#1E293B","#334155","#475569","#64748B","#94A3B8"],
      particleSize: 12, particleOpacity: 82, particleColorMode: "随机轻变化",
      particleGravity: 4, particleBounce: 8,
      ripple: true, rippleStyle: "单环", rippleSize: 48, rippleColor: "#334155",
      rippleOpacity: 42, rippleDuration: 540,
      sound: false, shake: 14, cursorOverride: "跟随当前状态",
    },
    doubleClick: {
      textKind: "数字飘字", textColor: "#1E293B", fontSize: 22, textWeight: "加粗",
      textEasing: "线性", textShadow: "无", textFontFamily: "等宽字体",
      particle: true, particleStyle: "方块", particleCount: 26, particleSpread: 66,
      particlePalette: ["#1E293B","#334155","#475569","#64748B"],
      particleSize: 14, particleOpacity: 86, particleBounce: 12,
      ripple: true, rippleStyle: "双环", rippleSize: 56, rippleColor: "#334155",
      rippleOpacity: 50, rippleDuration: 600,
      sound: false, shake: 22,
    },
    wheel: {
      particle: true, particleStyle: "方块", particlePalette: ["#475569","#64748B","#94A3B8"],
      particleCount: 8, ripple: true, rippleColor: "#475569", rippleStyle: "单环",
      textColor: "#475569", sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "单环", rippleColor: "#94A3B8", rippleOpacity: 24,
      textEnabled: true, textKind: "文本飘字", textTags: ["□", "■", "▣"], textTagPlayMode: "随机显示",
      textColor: "#475569", textFontFamily: "等宽字体", fontSize: 14, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "方块", particlePalette: ["#334155","#475569","#64748B"],
      particleCount: 12, ripple: true, rippleColor: "#475569", rippleStyle: "单环",
      textColor: "#475569", sound: false,
    },
    longPress: {
      particle: true, particleStyle: "方块", particlePalette: ["#1E293B","#334155","#475569"],
      particleCount: 16, particleBounce: 14, ripple: true, rippleColor: "#334155",
      rippleStyle: "双环", textColor: "#1E293B", sound: false, textFontFamily: "等宽字体",
    },
  },
  drift: {
    leftClick: {
      particle: true, particleStyle: "点状粒子",
      particleMotionMode: "orbital", orbitalCount: 8, orbitalRadius: 28, orbitalSpeed: 2,
      particlePalette: ["#0D9488","#14B8A6","#5EEAD4","#99F6E4"],
      particleSize: 10, particleOpacity: 80, particleColorMode: "随机轻变化",
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#14B8A6",
      rippleSize: 44, rippleOpacity: 28,
      textEnabled: false,
      sound: false, shake: 0,
      cursorGlowColor: "#14B8A6",
      cursorTrailEnabled: true, cursorTrailCount: 3, cursorTrailOpacity: 28,
    },
    doubleClick: {
      particle: true, particleStyle: "点状粒子",
      particleMotionMode: "orbital", orbitalCount: 12, orbitalRadius: 34, orbitalSpeed: 3,
      particlePalette: ["#0D9488","#14B8A6","#5EEAD4"],
      particleSize: 12, particleOpacity: 86,
      ripple: true, rippleStyle: "双环", rippleColor: "#14B8A6",
      rippleSize: 52, rippleOpacity: 36,
      textEnabled: false, sound: false,
      cursorGlowColor: "#14B8A6",
    },
    wheel: {
      particle: true, particleStyle: "点状粒子", particleCount: 6,
      particlePalette: ["#5EEAD4","#99F6E4"],
      ripple: true, rippleColor: "#14B8A6", rippleStyle: "单环",
      textEnabled: false, sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#5EEAD4", rippleOpacity: 20,
      cursorGlowColor: "#5EEAD4",
      textEnabled: false, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "点状粒子", particleCount: 8,
      particlePalette: ["#14B8A6","#5EEAD4"],
      ripple: true, rippleColor: "#14B8A6", rippleStyle: "双环",
      textEnabled: false, sound: false,
    },
    longPress: {
      particle: true, particleStyle: "点状粒子",
      particleMotionMode: "orbital", orbitalCount: 10, orbitalRadius: 30, orbitalSpeed: 1,
      particlePalette: ["#0D9488","#14B8A6","#5EEAD4"],
      particleSize: 10,
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#14B8A6",
      textEnabled: false, sound: false,
    },
  },
  molten: {
    leftClick: {
      particle: true, particleStyle: "火花", particleDirection: "向上喷发",
      particleCount: 28, particleSpread: 60,
      particlePalette: ["#F97316","#FB923C","#FBBF24","#FEF08A","#FDE68A"],
      particleSize: 14, particleOpacity: 90, particleColorMode: "随机轻变化",
      particleGravity: 12, particleBounce: 6,
      ripple: true, rippleStyle: "能量脉冲", rippleColor: "#F97316",
      rippleSize: 60, rippleOpacity: 60,
      textEnabled: true, textKind: "数字飘字", textContent: "+1",
      textColor: "#EA580C", fontSize: 22, textWeight: "加粗", textShadow: "清晰", textEasing: "弹性",
      textGradient: true, textGradientStart: "#F97316", textGradientEnd: "#FBBF24",
      sound: true, volume: 56, shake: 32,
      cursorGlowColor: "#F97316",
      cursorTrailEnabled: true, cursorTrailCount: 4, cursorTrailOpacity: 40,
    },
    doubleClick: {
      particle: true, particleStyle: "火花", particleDirection: "向上喷发",
      particleCount: 36, particleSpread: 72,
      particlePalette: ["#F97316","#FB923C","#FBBF24","#FEF08A"],
      particleSize: 16, particleOpacity: 94,
      particleGravity: 16, particleBounce: 10,
      ripple: true, rippleStyle: "回声环", rippleColor: "#FB923C",
      rippleSize: 72, rippleOpacity: 68,
      textGradient: true, textGradientStart: "#F97316", textGradientEnd: "#FBBF24",
      fontSize: 24,
      animationEnabled: true, animationStyle: "星光闪耀", animationColor: "#F97316",
      animationDuration: 640, animationGlow: true,
      sound: true, volume: 64, shake: 42,
    },
    wheel: {
      particle: true, particleStyle: "火花", particleCount: 8,
      particlePalette: ["#FB923C","#FBBF24"], particleGravity: 8,
      ripple: true, rippleColor: "#F97316", rippleStyle: "单环",
      textEnabled: false, sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#FBBF24", rippleOpacity: 24,
      cursorGlowColor: "#FBBF24",
      textEnabled: true, textKind: "文本飘字",
      textTags: ["✦", "·", "●"], textTagPlayMode: "随机显示",
      textColor: "#F97316", fontSize: 14, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "火花", particleCount: 14, particleGravity: 10,
      particlePalette: ["#F97316","#FB923C","#FBBF24"],
      ripple: true, rippleColor: "#F97316", rippleStyle: "双环",
      textColor: "#EA580C", sound: false,
    },
    longPress: {
      particle: true, particleStyle: "火花", particleCount: 20,
      particleGravity: 18, particleBounce: 8,
      particlePalette: ["#F97316","#FB923C","#FBBF24"],
      ripple: true, rippleStyle: "能量脉冲", rippleColor: "#FB923C",
      textColor: "#EA580C",
      animationEnabled: true, animationStyle: "聚焦脉冲", animationColor: "#F97316",
      animationDuration: 520,
      sound: true, volume: 48,
    },
  },
  sunset: {
    leftClick: {
      particle: true, particleStyle: "钻石",
      particleCount: 20, particleSpread: 64,
      particlePalette: ["#F43F5E","#FB7185","#FDA4AF","#FBCFE8","#FFF1F2"],
      particleSize: 12, particleOpacity: 82, particleColorMode: "随机轻变化",
      particleGravity: 4, particleWind: 2, particleBounce: 8,
      ripple: true, rippleStyle: "回声环", rippleColor: "#FB7185",
      rippleSize: 52, rippleOpacity: 44,
      textEnabled: true, textKind: "数字飘字", textContent: "+1",
      textColor: "#BE185D", fontSize: 20, textWeight: "加粗", textEasing: "弹跳", textShadow: "柔和",
      textGradient: true, textGradientStart: "#F43F5E", textGradientEnd: "#FB923C",
      sound: false, shake: 0,
      cursorGlowColor: "#FB7185",
      cursorTrailEnabled: true, cursorTrailCount: 3, cursorTrailOpacity: 32,
    },
    doubleClick: {
      particle: true, particleStyle: "钻石",
      particleCount: 28, particleSpread: 76,
      particlePalette: ["#F43F5E","#FB7185","#FDA4AF","#FBCFE8"],
      particleSize: 14, particleOpacity: 88,
      particleGravity: 6, particleWind: 3, particleBounce: 12,
      ripple: true, rippleStyle: "双环", rippleColor: "#FB7185",
      rippleSize: 62, rippleOpacity: 52,
      textGradient: true, textGradientStart: "#F43F5E", textGradientEnd: "#FB923C",
      fontSize: 22,
      animationEnabled: true, animationStyle: "弹跳徽记", animationColor: "#FB7185",
      animationDuration: 600,
      sound: false,
    },
    wheel: {
      particle: true, particleStyle: "钻石", particleCount: 8,
      particlePalette: ["#FDA4AF","#FBCFE8"],
      particleGravity: 6, particleWind: 4,
      ripple: true, rippleColor: "#FB7185", rippleStyle: "柔和面波",
      textEnabled: false, sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#FDA4AF", rippleOpacity: 22,
      cursorGlowColor: "#FDA4AF",
      textEnabled: true, textKind: "文本飘字",
      textTags: ["✦", "·", "◦"], textTagPlayMode: "随机显示",
      textColor: "#BE185D", fontSize: 14, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "钻石", particleCount: 12,
      particlePalette: ["#FB7185","#FDA4AF"], particleGravity: 4,
      ripple: true, rippleColor: "#FB7185", rippleStyle: "双环",
      textColor: "#BE185D", sound: false,
    },
    longPress: {
      particle: true, particleStyle: "钻石", particleCount: 18,
      particleGravity: 10, particleBounce: 14,
      particlePalette: ["#F43F5E","#FB7185","#FDA4AF"],
      ripple: true, rippleStyle: "回声环", rippleColor: "#FB7185",
      textColor: "#BE185D",
      animationEnabled: true, animationStyle: "聚焦脉冲", animationColor: "#FB7185",
      sound: false,
    },
  },
};

export function getDefaultActionConfigs(themeId) {
  const themeOverrides = THEME_ACTION_OVERRIDES[themeId] || {};
  return Object.fromEntries(
    Object.entries(ACTION_CONFIG_PRESETS).map(([actionId, config]) => [
      actionId,
      {
        ...cloneActionConfig(config),
        ...(themeOverrides[actionId] || {}),
      },
    ])
  );
}

export function getTimingFieldMeta(actionId) {
  if (actionId === "longPress") {
    return { label: "长按阈值", hint: "按住多久以后才算长按。", min: 200, max: 900 };
  }
  if (actionId === "doubleClick") {
    return { label: "双击间隔", hint: "两次点击之间允许的最大间隔。", min: 180, max: 520 };
  }
  if (actionId === "hover") {
    return { label: "停留阈值", hint: "鼠标停多久之后再触发 hover 效果。", min: 80, max: 700 };
  }
  if (actionId === "wheel") {
    return { label: "合并间隔", hint: "连续滚动时，多久合并为一次反馈。", min: 80, max: 520 };
  }
  return { label: "触发延迟", hint: "动作识别后，延迟多久开始反馈。", min: 0, max: 320 };
}

export function getConflictsForAction(actionId, actionConfigs) {
  const current = actionConfigs[actionId];
  const conflicts = [];

  if (actionId === "longPress" && current.sound && actionConfigs.leftClick.sound) {
    conflicts.push("长按和左键单击都在使用音效，后续需要明确谁先触发。");
  }

  if (!current.textEnabled && !current.particle && !current.ripple && !current.sound && !current.animationEnabled && !current.imageEnabled) {
    conflicts.push("当前动作没有绑定任何反馈，用户点击时会感觉没效果。");
  }

  return conflicts;
}
