const NUMERIC_LIMITS = {
  fontSize: [12, 36],
  textDuration: [240, 1800],
  textOpacity: [20, 100],
  textOffsetX: [-72, 72],
  textOffsetY: [-72, 24],
  textOutlineWidth: [0, 3],
  particleCount: [0, 40],
  particleSpread: [8, 120],
  particleDuration: [180, 1600],
  particleSize: [4, 28],
  particleOpacity: [20, 100],
  rippleSize: [20, 140],
  rippleDuration: [180, 1600],
  rippleOpacity: [10, 100],
  rippleLineWidth: [1, 6],
  volume: [0, 100],
  playbackRate: [70, 130],
  soundDelay: [0, 500],
  soundFadeOut: [0, 300],
  shake: [0, 90],
  cursorSize: [32, 64],
  holdMs: [0, 900],
  animationDuration: [120, 1800],
  animationScale: [50, 180],
  animationOpacity: [10, 100],
  animationOffsetX: [-72, 72],
  animationOffsetY: [-72, 72],
  imageDuration: [120, 1800],
  imageSize: [24, 180],
  imageOpacity: [10, 100],
  imageOffsetX: [-120, 120],
  imageOffsetY: [-120, 120],
};

const ENUM_OPTIONS = {
  triggerTiming: ["按下时", "抬起时", "菜单弹出前", "第二次按下时", "第二次抬起后", "按住达到阈值", "松开后触发", "滚动开始时", "连续滚动中", "进入时", "停留后"],
  triggerZone: ["当前页面可点击区域", "仅按钮和链接", "全部可交互元素", "右键菜单前", "可交互元素", "空白区域", "双击命中区域", "主操作按钮", "内容卡片", "按住后释放", "长按可交互元素", "全局长按区", "向上 / 向下滚轮", "仅向上滚动", "仅向下滚动", "进入可交互元素", "全页面 hover"],
  textKind: ["数字飘字", "文本飘字"],
  textStyle: ["阿拉伯数字 (1, 2, 3)", "中文数字 (一, 二, 三)", "英文单词 (one, two, three)"],
  textMode: ["默认模式 (+1)", "模板模式"],
  textTagPlayMode: ["按顺序显示", "随机显示"],
  textEasing: ["线性", "缓入", "缓出", "缓入缓出", "弹跳", "弹性"],
  textWeight: ["常规", "中等", "加粗"],
  textShadow: ["无", "柔和", "清晰"],
  particleStyle: ["点状粒子", "碎屑粒子", "火花", "星光", "钻石", "心形", "方块", "三角"],
  particleDirection: ["四周扩散", "向上喷发", "沿点击方向"],
  particleColorMode: ["跟随主题", "跟随飘字色", "随机轻变化"],
  rippleStyle: ["单环", "双环", "柔和面波", "脉冲波纹", "回声环", "能量脉冲"],
  rippleEasing: ["线性", "缓出", "缓入缓出", "弹性"],
  soundTriggerMode: ["每次触发", "连击叠加", "节流播放"],
  soundBlendMode: ["保持原音量", "压低页面音频", "仅插件音效"],
  soundFile: ["woodfish-soft.wav", "woodfish-deep.wav", "tick-light.wav"],
  cursorOverride: ["跟随当前状态", "木鱼（继承默认）", "木鱼（增强态）", "木鱼（按压态）", "切换到 pointer"],
  animationStyle: ["聚焦脉冲", "斜切闪片", "弹跳徽记", "漩涡旋转", "星光闪耀", "轨道环绕", "螺旋上升"],
};

const BOOLEAN_FIELDS = new Set([
  "textEnabled",
  "comboEnabled",
  "particle",
  "ripple",
  "sound",
  "animationEnabled",
  "imageEnabled",
]);

const STRING_FIELDS = new Set([
  "textTemplate",
  "textContent",
  "textColor",
  "imageDataUrl",
]);

const ARRAY_FIELDS = new Set(["textTags"]);

const AI_SCHEME_PATCH_FIELDS = new Set([
  ...Object.keys(NUMERIC_LIMITS),
  ...Object.keys(ENUM_OPTIONS),
  ...BOOLEAN_FIELDS,
  ...STRING_FIELDS,
  ...ARRAY_FIELDS,
]);

const DEFAULT_API_ENDPOINT = "/api/ai/scheme-proposals";
const VALID_PROPOSAL_MODES = new Set(["modify_action", "generate_theme", "explain_config", "tune_proposal"]);
const AI_EXTENSION_VERSION = "0.1.0";
const AI_SCHEMA_VERSION = "2026-05-20";
const MAX_PROPOSAL_CONTEXT_BYTES = 8 * 1024;

const FIELD_LABELS = {
  triggerTiming: "触发时机",
  triggerZone: "触发区域",
  textEnabled: "飘字",
  textKind: "飘字类型",
  textStyle: "数字样式",
  textMode: "飘字模式",
  textTemplate: "模板文案",
  textContent: "飘字文案",
  textTags: "候选文案",
  textTagPlayMode: "候选播放",
  textColor: "主色",
  fontSize: "字号",
  textDuration: "飘字时长",
  textEasing: "飘字缓动",
  textWeight: "字体粗细",
  textShadow: "文字阴影",
  textOpacity: "飘字透明度",
  textOffsetX: "飘字水平偏移",
  textOffsetY: "飘字垂直偏移",
  textOutlineWidth: "文字描边",
  comboEnabled: "连击累加",
  particle: "粒子",
  particleCount: "粒子数量",
  particleSpread: "粒子范围",
  particleDuration: "粒子时长",
  particleSize: "粒子尺寸",
  particleOpacity: "粒子透明度",
  particleStyle: "粒子样式",
  particleDirection: "粒子方向",
  particleColorMode: "粒子颜色",
  ripple: "波纹",
  rippleSize: "波纹尺寸",
  rippleDuration: "波纹时长",
  rippleOpacity: "波纹透明度",
  rippleStyle: "波纹样式",
  rippleEasing: "波纹缓动",
  rippleLineWidth: "波纹线宽",
  sound: "音效",
  volume: "音量",
  playbackRate: "播放速度",
  soundDelay: "音效延迟",
  soundFadeOut: "淡出时长",
  soundTriggerMode: "播放策略",
  soundBlendMode: "混音模式",
  soundFile: "音效文件",
  shake: "震动强度",
  cursorOverride: "光标反馈",
  cursorSize: "光标尺寸",
  holdMs: "触发延迟",
  animationEnabled: "动画",
  animationStyle: "动画样式",
  animationDuration: "动画时长",
  animationScale: "动画缩放",
  animationOpacity: "动画透明度",
  animationOffsetX: "动画水平偏移",
  animationOffsetY: "动画垂直偏移",
  imageEnabled: "图像",
  imageDataUrl: "图像数据",
  imageDuration: "图像时长",
  imageSize: "图像尺寸",
  imageOpacity: "图像透明度",
  imageOffsetX: "图像水平偏移",
  imageOffsetY: "图像垂直偏移",
};

const AI_TASK_MODES = {
  modify_action: "修改当前动作",
  explain_config: "解释配置",
  generate_theme: "生成主题方案",
  tune_proposal: "微调上一版方案",
};

export {
  AI_EXTENSION_VERSION,
  AI_SCHEMA_VERSION,
  AI_SCHEME_PATCH_FIELDS,
  AI_TASK_MODES,
  ARRAY_FIELDS,
  BOOLEAN_FIELDS,
  DEFAULT_API_ENDPOINT,
  ENUM_OPTIONS,
  FIELD_LABELS,
  MAX_PROPOSAL_CONTEXT_BYTES,
  NUMERIC_LIMITS,
  STRING_FIELDS,
  VALID_PROPOSAL_MODES,
};
