const ACTION_CONFIG_SHARED_DEFAULTS = {
  textStyle: "阿拉伯数字 (1, 2, 3)",
  textMode: "默认模式 (+1)",
  textTemplate: "${number}",
  textTagPlayMode: "按顺序显示",
  textOpacity: 100,
  textFontFamily: "系统默认",
  textOutlineWidth: 0,
  comboEnabled: false,
  textOffsetX: 0,
  particleStyle: "点状粒子",
  particleColorMode: "跟随主题",
  particlePalette: ["#FBBF24", "#F59E0B", "#FDE68A", "#FCD34D", "#FEF3C7"],
  particleGravity: 0,
  particleWind: 0,
  particleBounce: 0,
  particleTrail: false,
  rippleStyle: "单环",
  rippleLineWidth: 2,
  rippleColor: "#F59E0B",
  soundBlendMode: "保持原音量",
  playbackRate: 100,
  soundDelay: 0,
  animationEnabled: false,
  animationStyle: "聚焦脉冲",
  animationDuration: 720,
  animationEasing: "缓出",
  animationScale: 100,
  animationOpacity: 100,
  animationOffsetX: 0,
  animationOffsetY: -10,
  animationColor: "#F59E0B",
  animationGlow: false,
  imageEnabled: false,
  imageDataUrl: "",
  imageDuration: 780,
  imageSize: 56,
  imageOpacity: 100,
  imageOffsetX: 0,
  imageOffsetY: -18,
  textGradient: false,
  textGradientStart: "#FBBF24",
  textGradientEnd: "#EC4899",
  cursorTrailEnabled: false,
  cursorTrailCount: 5,
  cursorTrailOpacity: 50,
  cursorGlowColor: "",
  comboWindowMs: 900,
  textDelay: 0,
  rippleDelay: 0,
  particleDelay: 0,
  animationDelay: 0,
  imageDelay: 0,
};

function createActionConfig(overrides) {
  return {
    ...ACTION_CONFIG_SHARED_DEFAULTS,
    ...overrides,
    textTags: [...(overrides.textTags || [])],
  };
}

function cloneActionConfig(config) {
  return {
    ...config,
    textTags: [...(config.textTags || [])],
  };
}

const ACTION_CONFIG_PRESETS = {
  leftClick: createActionConfig({
    textKind: "数字飘字",
    textEnabled: true,
    textContent: "+1",
    textTags: ["功德 +1", "继续点击", "已触发"],
    textColor: "#B45309",
    textDuration: 1000,
    textEasing: "弹跳",
    textWeight: "加粗",
    textShadow: "柔和",
    comboEnabled: true,
    textOffsetY: -28,
    particle: true,
    particleCount: 22,
    particleSpread: 62,
    particleStyle: "火花",
    particleDirection: "四周扩散",
    particleDuration: 780,
    particleSize: 14,
    particleOpacity: 88,
    particleGravity: 8,
    particleBounce: 14,
    ripple: true,
    rippleSize: 72,
    rippleDuration: 860,
    rippleStyle: "回声环",
    rippleEasing: "缓出",
    rippleOpacity: 72,
    sound: true,
    fontSize: 24,
    volume: 72,
    soundFadeOut: 80,
    soundTriggerMode: "每次触发",
    shake: 48,
    cursorOverride: "木鱼（继承默认）",
    cursorSize: 48,
    cursorTrailEnabled: true,
    cursorTrailCount: 4,
    cursorTrailOpacity: 36,
    cursorGlowColor: "#F59E0B",
    imageEnabled: false,
    triggerTiming: "抬起时",
    triggerZone: "当前页面可点击区域",
    holdMs: 0,
    soundFile: "woodfish-soft.wav",
  }),
  rightClick: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "menu",
    textTags: ["展开菜单", "右键操作", "更多选项"],
    textColor: "#475569",
    textDuration: 820,
    textEasing: "缓出",
    textWeight: "中等",
    textShadow: "无",
    textOffsetY: -18,
    particle: true,
    particleCount: 14,
    particleSpread: 40,
    particleDirection: "四周扩散",
    particleDuration: 560,
    particleSize: 10,
    particleOpacity: 72,
    ripple: true,
    rippleSize: 50,
    rippleDuration: 560,
    rippleStyle: "双环",
    rippleEasing: "缓出",
    rippleOpacity: 62,
    sound: false,
    fontSize: 18,
    volume: 60,
    soundFadeOut: 40,
    soundTriggerMode: "节流播放",
    shake: 22,
    cursorOverride: "跟随当前状态",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "菜单弹出前",
    triggerZone: "右键菜单前",
    holdMs: 0,
    soundFile: "tick-light.wav",
  }),
  doubleClick: createActionConfig({
    textKind: "数字飘字",
    textStyle: "英文单词 (one, two, three)",
    textMode: "模板模式",
    textTemplate: "combo ${number}",
    textEnabled: true,
    textContent: "combo",
    textTags: ["双击完成", "连击命中", "combo"],
    textTagPlayMode: "随机显示",
    textColor: "#0F766E",
    textDuration: 1100,
    textEasing: "弹性",
    textWeight: "加粗",
    textOutlineWidth: 1,
    textShadow: "柔和",
    comboEnabled: true,
    textOffsetY: -30,
    particle: true,
    particleCount: 26,
    particleSpread: 74,
    particleStyle: "火花",
    particleDirection: "四周扩散",
    particleColorMode: "随机轻变化",
    particlePalette: ["#14B8A6", "#0F766E", "#5EEAD4", "#99F6E4", "#CCFBF1"],
    particleDuration: 980,
    particleSize: 16,
    particleOpacity: 96,
    ripple: true,
    rippleSize: 84,
    rippleDuration: 940,
    rippleStyle: "双环",
    rippleEasing: "弹性",
    rippleLineWidth: 3,
    rippleOpacity: 84,
    rippleColor: "#14B8A6",
    sound: true,
    fontSize: 24,
    volume: 80,
    playbackRate: 104,
    soundFadeOut: 90,
    soundTriggerMode: "连击叠加",
    soundBlendMode: "压低页面音频",
    shake: 52,
    cursorOverride: "木鱼（增强态）",
    cursorSize: 52,
    cursorTrailEnabled: true,
    cursorTrailCount: 5,
    cursorTrailOpacity: 42,
    cursorGlowColor: "#14B8A6",
    imageEnabled: false,
    triggerTiming: "第二次抬起后",
    triggerZone: "双击命中区域",
    holdMs: 320,
    soundFile: "woodfish-deep.wav",
  }),
  longPress: createActionConfig({
    textKind: "文本飘字",
    textStyle: "中文数字 (一, 二, 三)",
    textEnabled: false,
    textContent: "蓄",
    textTags: ["按住中", "蓄力完成", "松开触发"],
    textColor: "#7C3AED",
    textDuration: 900,
    textEasing: "缓入缓出",
    textOpacity: 94,
    textWeight: "中等",
    textShadow: "柔和",
    textOffsetY: -22,
    particle: true,
    particleCount: 16,
    particleSpread: 48,
    particleStyle: "碎屑粒子",
    particleDirection: "向上喷发",
    particlePalette: ["#A78BFA", "#7C3AED", "#C4B5FD", "#DDD6FE", "#EDE9FE"],
    particleDuration: 740,
    particleSize: 12,
    particleOpacity: 78,
    ripple: true,
    rippleSize: 62,
    rippleDuration: 780,
    rippleStyle: "柔和面波",
    rippleEasing: "缓入缓出",
    rippleOpacity: 56,
    rippleColor: "#A78BFA",
    sound: true,
    fontSize: 20,
    volume: 72,
    playbackRate: 92,
    soundDelay: 60,
    soundFadeOut: 120,
    soundTriggerMode: "每次触发",
    soundBlendMode: "压低页面音频",
    shake: 58,
    cursorOverride: "木鱼（按压态）",
    cursorSize: 50,
    imageEnabled: false,
    triggerTiming: "松开后触发",
    triggerZone: "按住后释放",
    holdMs: 560,
    soundFile: "woodfish-deep.wav",
  }),
  wheel: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "roll",
    textTags: ["向上滚动", "向下滚动", "继续滚动"],
    textTagPlayMode: "随机显示",
    textColor: "#0284C7",
    textDuration: 700,
    textEasing: "线性",
    textOpacity: 90,
    textWeight: "常规",
    textShadow: "无",
    textOffsetY: -14,
    particle: true,
    particleCount: 10,
    particleSpread: 36,
    particleDirection: "四周扩散",
    particleColorMode: "跟随飘字色",
    particleDuration: 460,
    particleSize: 10,
    particleOpacity: 72,
    ripple: true,
    rippleSize: 38,
    rippleDuration: 500,
    rippleStyle: "单环",
    rippleEasing: "线性",
    rippleLineWidth: 1,
    rippleOpacity: 46,
    rippleColor: "#0284C7",
    sound: false,
    fontSize: 16,
    volume: 40,
    playbackRate: 110,
    soundFadeOut: 30,
    soundTriggerMode: "节流播放",
    shake: 16,
    cursorOverride: "跟随当前状态",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "连续滚动中",
    triggerZone: "向上 / 向下滚轮",
    holdMs: 180,
    soundFile: "tick-light.wav",
  }),
  hover: createActionConfig({
    textKind: "文本飘字",
    textEnabled: false,
    textContent: "hover",
    textTags: ["已聚焦", "经过目标", "可点击"],
    textTagPlayMode: "随机显示",
    textColor: "#475569",
    textDuration: 680,
    textEasing: "缓入缓出",
    textOpacity: 88,
    textWeight: "常规",
    textShadow: "无",
    textOffsetY: -12,
    particle: false,
    particleCount: 8,
    particleSpread: 24,
    particleDirection: "向上喷发",
    particleDuration: 420,
    particleSize: 8,
    particleOpacity: 60,
    ripple: true,
    rippleSize: 34,
    rippleDuration: 440,
    rippleStyle: "柔和面波",
    rippleEasing: "缓入缓出",
    rippleLineWidth: 1,
    rippleOpacity: 32,
    rippleColor: "#94A3B8",
    sound: false,
    fontSize: 16,
    volume: 0,
    soundFadeOut: 0,
    soundTriggerMode: "节流播放",
    shake: 0,
    cursorOverride: "切换到 pointer",
    cursorSize: 44,
    imageEnabled: false,
    triggerTiming: "停留后",
    triggerZone: "进入可交互元素",
    holdMs: 220,
    soundFile: "tick-light.wav",
  }),
};

const THEME_ACTION_OVERRIDES = {
  "demo-highlight": {
    leftClick: {
      textColor: "#38BDF8", fontSize: 28, textWeight: "加粗", textShadow: "清晰", textEasing: "弹性",
      textGradient: true, textGradientStart: "#818CF8", textGradientEnd: "#06B6D4",
      particle: true, particleStyle: "星光", particleCount: 36, particleSpread: 86,
      particlePalette: ["#06B6D4","#22D3EE","#818CF8","#A78BFA","#38BDF8"],
      particleSize: 16, particleOpacity: 94, particleColorMode: "随机轻变化", particleGravity: -10,
      ripple: true, rippleStyle: "能量脉冲", rippleSize: 92, rippleOpacity: 82, rippleColor: "#818CF8",
      animationEnabled: true, animationStyle: "螺旋上升", animationDuration: 780, animationGlow: true, animationColor: "#818CF8",
      cursorTrailEnabled: true, cursorTrailCount: 8, cursorTrailOpacity: 58, cursorGlowColor: "#818CF8",
      sound: true, volume: 82, shake: 64,
    },
    doubleClick: {
      textColor: "#38BDF8", fontSize: 30, textWeight: "加粗", textShadow: "清晰",
      textGradient: true, textGradientStart: "#A78BFA", textGradientEnd: "#06B6D4",
      particle: true, particleStyle: "星光", particleCount: 44, particleSpread: 94,
      particlePalette: ["#06B6D4","#22D3EE","#818CF8","#A78BFA"],
      particleSize: 18, particleOpacity: 96, particleGravity: -14,
      ripple: true, rippleStyle: "回声环", rippleSize: 104, rippleOpacity: 86, rippleColor: "#A78BFA",
      animationEnabled: true, animationStyle: "星光闪耀", animationDuration: 820, animationGlow: true, animationColor: "#06B6D4",
      cursorTrailEnabled: true, cursorTrailCount: 10, cursorTrailOpacity: 64,
      sound: true, volume: 88, shake: 74,
    },
    wheel: {
      particle: true, particleStyle: "星光", particlePalette: ["#06B6D4","#22D3EE","#818CF8"],
      particleCount: 16, particleColorMode: "随机轻变化", particleGravity: -6,
      ripple: true, rippleColor: "#818CF8", rippleStyle: "双环",
      animationEnabled: true, animationStyle: "聚焦脉冲", animationColor: "#06B6D4",
    },
    hover: {
      animationEnabled: true, animationStyle: "聚焦脉冲", animationColor: "#06B6D4", animationDuration: 480,
      cursorTrailEnabled: true, cursorTrailOpacity: 38, cursorGlowColor: "#38BDF8",
      ripple: true, rippleColor: "#818CF8", rippleStyle: "柔和面波", rippleOpacity: 36,
      textEnabled: true, textKind: "文本飘字", textTags: ["★", "◈", "✦"], textTagPlayMode: "随机显示",
      textColor: "#38BDF8", fontSize: 16,
    },
    rightClick: {
      particle: true, particleStyle: "星光", particleCount: 20, particleGravity: -8,
      particlePalette: ["#06B6D4","#22D3EE","#818CF8"],
      ripple: true, rippleColor: "#818CF8", rippleStyle: "双环", shake: 28,
    },
    longPress: {
      particle: true, particleStyle: "星光", particleCount: 28, particleGravity: -12,
      particlePalette: ["#06B6D4","#22D3EE","#818CF8","#A78BFA"],
      ripple: true, rippleStyle: "能量脉冲", rippleColor: "#818CF8",
      animationEnabled: true, animationStyle: "漩涡旋转", animationColor: "#A78BFA", animationDuration: 760, animationGlow: true,
      textColor: "#38BDF8",
    },
  },
  petal: {
    leftClick: {
      textStyle: "中文数字 (一, 二, 三)", textColor: "#E11D48", fontSize: 22, textWeight: "加粗",
      textEasing: "弹跳", textShadow: "柔和",
      textGradient: true, textGradientStart: "#F43F5E", textGradientEnd: "#FB923C",
      particle: true, particleStyle: "钻石", particleCount: 24, particleSpread: 68,
      particlePalette: ["#F97316","#FB923C","#FBBF24","#F59E0B","#FCD34D"],
      particleSize: 13, particleOpacity: 86, particleGravity: 6, particleBounce: 12,
      ripple: true, rippleStyle: "回声环", rippleColor: "#FB923C", rippleSize: 62, rippleOpacity: 48,
      sound: true, volume: 62, shake: 36, soundFile: "woodfish-soft.wav",
    },
    doubleClick: {
      textStyle: "中文数字 (一, 二, 三)", textColor: "#E11D48", fontSize: 24, textWeight: "加粗",
      textEasing: "弹性", textShadow: "清晰",
      textGradient: true, textGradientStart: "#F43F5E", textGradientEnd: "#FB923C",
      particle: true, particleStyle: "钻石", particleCount: 30, particleSpread: 76,
      particlePalette: ["#F97316","#FB923C","#FBBF24","#F59E0B"],
      particleSize: 15, particleOpacity: 90, particleBounce: 18,
      ripple: true, rippleStyle: "回声环", rippleColor: "#FB923C", rippleSize: 72, rippleOpacity: 56,
      sound: true, volume: 68, shake: 44, soundFile: "woodfish-soft.wav",
    },
    wheel: {
      particle: true, particleStyle: "钻石", particlePalette: ["#FB923C","#FBBF24","#F59E0B"],
      particleBounce: 8, ripple: true, rippleColor: "#FB923C", rippleStyle: "柔和面波",
      textColor: "#E11D48", sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "柔和面波", rippleColor: "#FB923C", rippleOpacity: 32,
      textEnabled: true, textKind: "文本飘字", textTags: ["♢", "◆", "◇"], textTagPlayMode: "随机显示",
      textColor: "#E11D48", fontSize: 16, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "钻石", particlePalette: ["#FB923C","#FBBF24"],
      particleBounce: 12, ripple: true, rippleColor: "#FB923C", rippleStyle: "双环",
      textColor: "#E11D48", sound: false,
    },
    longPress: {
      particle: true, particleStyle: "钻石", particlePalette: ["#F97316","#FB923C","#FBBF24"],
      particleBounce: 22, ripple: true, rippleColor: "#FB923C", rippleStyle: "柔和面波",
      textColor: "#E11D48", sound: true, volume: 56,
    },
  },
  "star-burst": {
    leftClick: {
      particleStyle: "星光", particlePalette: ["#FBBF24","#F59E0B","#FDE68A","#FEF3C7","#FCD34D"],
      particleCount: 32, particleSpread: 82, particleBounce: 22, particleSize: 16, particleOpacity: 94,
      particleColorMode: "随机轻变化",
      rippleStyle: "脉冲波纹", rippleSize: 82, rippleOpacity: 78, rippleColor: "#FBBF24",
      textColor: "#B45309", fontSize: 24, textWeight: "加粗", textEasing: "弹跳", textShadow: "清晰",
      shake: 62, volume: 82, cursorSize: 52,
    },
    doubleClick: {
      particleStyle: "星光", particlePalette: ["#FBBF24","#F59E0B","#FDE68A","#FEF3C7"],
      particleCount: 40, particleSpread: 90, particleBounce: 30, particleSize: 18, particleOpacity: 96,
      particleColorMode: "随机轻变化",
      rippleStyle: "回声环", rippleSize: 96, rippleOpacity: 86, rippleColor: "#F59E0B",
      textColor: "#B45309", fontSize: 26, textWeight: "加粗", textEasing: "弹性", textShadow: "清晰",
      shake: 74, volume: 88, cursorSize: 56,
    },
    wheel: { particleStyle: "星光", particle: true, particleCount: 16, particleSpread: 56, particleColorMode: "随机轻变化", particlePalette: ["#FBBF24","#FDE68A"], ripple: true, rippleColor: "#FBBF24", textColor: "#B45309" },
    hover: { ripple: true, rippleStyle: "柔和面波", rippleColor: "#FBBF24", textColor: "#B45309", textEnabled: true, textKind: "文本飘字", textTags: ["✨", "⭐", "🌟"], textTagPlayMode: "随机显示", fontSize: 18 },
    rightClick: { particleStyle: "星光", particle: true, particleCount: 18, rippleColor: "#FBBF24" },
    longPress: { particleStyle: "星光", particle: true, particleCount: 24, particleBounce: 28, rippleStyle: "能量脉冲", rippleColor: "#FBBF24", textColor: "#B45309" },
  },
  "neon-city": {
    leftClick: {
      textColor: "#06B6D4", fontSize: 22, textWeight: "加粗", textShadow: "清晰", textEasing: "弹性",
      textGradient: true, textGradientStart: "#06B6D4", textGradientEnd: "#8B5CF6",
      particleStyle: "火花", particlePalette: ["#06B6D4","#22D3EE","#818CF8","#A78BFA","#38BDF8"],
      particleCount: 26, particleSpread: 72, particleSize: 14, particleOpacity: 92,
      particleColorMode: "随机轻变化", particleGravity: -8,
      rippleStyle: "能量脉冲", rippleSize: 74, rippleOpacity: 76, rippleColor: "#06B6D4",
      animationEnabled: true, animationStyle: "漩涡旋转", animationColor: "#06B6D4", animationDuration: 680, animationGlow: true,
      cursorTrailEnabled: true, cursorTrailCount: 6, cursorTrailOpacity: 56, cursorGlowColor: "#06B6D4",
      shake: 58, volume: 72, cursorSize: 48,
    },
    doubleClick: {
      textColor: "#06B6D4", fontSize: 26, textWeight: "加粗", textShadow: "清晰",
      textGradient: true, textGradientStart: "#06B6D4", textGradientEnd: "#8B5CF6",
      particleStyle: "火花", particlePalette: ["#06B6D4","#22D3EE","#818CF8","#A78BFA"],
      particleCount: 36, particleSpread: 84, particleGravity: -10, particleSize: 16, particleOpacity: 94,
      rippleStyle: "回声环", rippleSize: 88, rippleOpacity: 82, rippleColor: "#06B6D4",
      animationEnabled: true, animationStyle: "螺旋上升", animationColor: "#8B5CF6", animationDuration: 780, animationGlow: true,
      cursorTrailEnabled: true, cursorTrailCount: 8, cursorTrailOpacity: 62,
      shake: 70, volume: 82, cursorSize: 52,
    },
    wheel: { particle: true, particleStyle: "火花", particlePalette: ["#06B6D4","#22D3EE","#818CF8"], particleCount: 12, particleColorMode: "随机轻变化", ripple: true, rippleColor: "#06B6D4", textColor: "#06B6D4" },
    hover: { animationEnabled: true, animationStyle: "聚焦脉冲", animationColor: "#06B6D4", animationDuration: 520, cursorTrailEnabled: true, cursorTrailOpacity: 42, ripple: true, rippleColor: "#06B6D4", rippleStyle: "柔和面波", rippleOpacity: 36, textEnabled: true, textKind: "文本飘字", textTags: ["⚡", "💎", "🌙"], textTagPlayMode: "随机显示", textColor: "#06B6D4", fontSize: 16 },
    rightClick: { particleStyle: "火花", particle: true, particleCount: 16, rippleColor: "#06B6D4" },
    longPress: { particle: true, particleStyle: "火花", particleGravity: -12, rippleStyle: "能量脉冲", rippleColor: "#06B6D4", animationEnabled: true, animationStyle: "星光闪耀", animationColor: "#06B6D4" },
  },
  "ink-wash": {
    leftClick: {
      textFontFamily: "楷体", textColor: "#1E293B", fontSize: 22, textWeight: "加粗", textShadow: "柔和",
      textEasing: "缓入缓出", textOpacity: 88,
      particleStyle: "碎屑粒子", particlePalette: ["#334155","#475569","#64748B","#94A3B8","#CBD5E1"],
      particleCount: 22, particleSpread: 66, particleGravity: 28, particleSize: 12, particleOpacity: 78,
      particleColorMode: "随机轻变化",
      rippleStyle: "柔和面波", rippleSize: 56, rippleOpacity: 38, rippleColor: "#64748B",
      animationEnabled: false, sound: false, shake: 24, textOutlineWidth: 1,
    },
    doubleClick: {
      textFontFamily: "楷体", textColor: "#1E293B", fontSize: 26, textWeight: "加粗", textShadow: "清晰",
      textEasing: "缓入缓出",
      particleStyle: "碎屑粒子", particlePalette: ["#334155","#475569","#64748B","#94A3B8"],
      particleCount: 30, particleSpread: 78, particleGravity: 34, particleSize: 14, particleOpacity: 84,
      rippleStyle: "回声环", rippleSize: 68, rippleOpacity: 46, rippleColor: "#475569",
      sound: false, shake: 34, textOutlineWidth: 1,
    },
    wheel: { particle: true, particleStyle: "碎屑粒子", particlePalette: ["#94A3B8","#CBD5E1"], particleGravity: 22, particleColorMode: "随机轻变化", ripple: true, rippleColor: "#64748B", textColor: "#475569", sound: false },
    hover: { ripple: true, rippleStyle: "柔和面波", rippleColor: "#94A3B8", rippleOpacity: 28, textColor: "#64748B", textEnabled: true, textKind: "文本飘字", textTags: ["墨", "笔", "书"], textTagPlayMode: "随机显示", textFontFamily: "楷体", fontSize: 16, sound: false },
    rightClick: { particle: true, particleStyle: "碎屑粒子", particleGravity: 18, rippleColor: "#64748B", sound: false },
    longPress: { particle: true, particleStyle: "碎屑粒子", particleGravity: 36, rippleColor: "#475569", sound: false, textFontFamily: "楷体" },
  },
  "mono-geo": {
    leftClick: {
      textKind: "数字飘字", textEnabled: true, textContent: "+1",
      textTags: ["+1", "+2", "+3"],
      textColor: "#1E293B", fontSize: 20, textWeight: "中等", textEasing: "线性", textShadow: "无",
      textFontFamily: "等宽字体", comboEnabled: true,
      particle: true, particleStyle: "方块", particleCount: 18, particleSpread: 56,
      particlePalette: ["#1E293B","#334155","#475569","#64748B","#94A3B8"],
      particleSize: 12, particleOpacity: 82, particleColorMode: "随机轻变化",
      particleGravity: 4, particleBounce: 8,
      ripple: true, rippleStyle: "单环", rippleSize: 48, rippleColor: "#334155",
      rippleOpacity: 42, rippleDuration: 540,
      sound: false, shake: 14, cursorOverride: "跟随当前状态",
    },
    doubleClick: {
      textKind: "数字飘字", textColor: "#1E293B", fontSize: 22, textWeight: "加粗",
      textEasing: "线性", textShadow: "无", textFontFamily: "等宽字体",
      particle: true, particleStyle: "方块", particleCount: 26, particleSpread: 66,
      particlePalette: ["#1E293B","#334155","#475569","#64748B"],
      particleSize: 14, particleOpacity: 86, particleBounce: 12,
      ripple: true, rippleStyle: "双环", rippleSize: 56, rippleColor: "#334155",
      rippleOpacity: 50, rippleDuration: 600,
      sound: false, shake: 22,
    },
    wheel: {
      particle: true, particleStyle: "方块", particlePalette: ["#475569","#64748B","#94A3B8"],
      particleCount: 8, ripple: true, rippleColor: "#475569", rippleStyle: "单环",
      textColor: "#475569", sound: false,
    },
    hover: {
      ripple: true, rippleStyle: "单环", rippleColor: "#94A3B8", rippleOpacity: 24,
      textEnabled: true, textKind: "文本飘字", textTags: ["□", "■", "▣"], textTagPlayMode: "随机显示",
      textColor: "#475569", textFontFamily: "等宽字体", fontSize: 14, sound: false,
    },
    rightClick: {
      particle: true, particleStyle: "方块", particlePalette: ["#334155","#475569","#64748B"],
      particleCount: 12, ripple: true, rippleColor: "#475569", rippleStyle: "单环",
      textColor: "#475569", sound: false,
    },
    longPress: {
      particle: true, particleStyle: "方块", particlePalette: ["#1E293B","#334155","#475569"],
      particleCount: 16, particleBounce: 14, ripple: true, rippleColor: "#334155",
      rippleStyle: "双环", textColor: "#1E293B", sound: false, textFontFamily: "等宽字体",
    },
  },
  "candy-land": {
    leftClick: {
      particleStyle: "钻石", particlePalette: ["#F43F5E","#FB923C","#FACC15","#34D399","#60A5FA","#C084FC"],
      particleCount: 30, particleSpread: 76, particleBounce: 36, particleTrail: true,
      particleSize: 15, particleOpacity: 92, particleColorMode: "随机轻变化",
      rippleStyle: "回声环", rippleSize: 72, rippleOpacity: 74, rippleColor: "#F43F5E",
      textColor: "#BE185D", fontSize: 22, textWeight: "加粗", textEasing: "弹跳", textShadow: "清晰",
      animationEnabled: true, animationStyle: "弹跳徽记", animationDuration: 620, animationColor: "#FB923C",
      shake: 52, volume: 76, cursorSize: 48,
    },
    doubleClick: {
      particleStyle: "心形", particlePalette: ["#F43F5E","#FB923C","#FACC15","#34D399","#60A5FA","#C084FC"],
      particleCount: 38, particleSpread: 86, particleBounce: 44, particleTrail: true,
      particleSize: 18, particleOpacity: 94, particleColorMode: "随机轻变化",
      rippleStyle: "能量脉冲", rippleSize: 84, rippleOpacity: 82, rippleColor: "#8B5CF6",
      textColor: "#BE185D", fontSize: 26, textWeight: "加粗", textEasing: "弹性", textShadow: "清晰",
      animationEnabled: true, animationStyle: "星光闪耀", animationDuration: 720, animationColor: "#FACC15",
      shake: 66, volume: 84, cursorSize: 52,
    },
    wheel: { particle: true, particleStyle: "钻石", particlePalette: ["#F43F5E","#FB923C","#FACC15"], particleBounce: 22, particleColorMode: "随机轻变化", ripple: true, rippleColor: "#F43F5E", textColor: "#BE185D" },
    hover: { animationEnabled: true, animationStyle: "弹跳徽记", animationColor: "#FB923C", animationDuration: 480, ripple: true, rippleColor: "#FB923C", rippleStyle: "柔和面波", textEnabled: true, textKind: "文本飘字", textTags: ["🍬", "🍭", "🎨"], textTagPlayMode: "随机显示", fontSize: 18, textColor: "#BE185D" },
    rightClick: { particle: true, particleStyle: "方块", particlePalette: ["#34D399","#60A5FA","#C084FC"], particleBounce: 18, rippleColor: "#34D399" },
    longPress: { particle: true, particleStyle: "三角", particlePalette: ["#FACC15","#FB923C","#F43F5E"], particleBounce: 38, rippleStyle: "脉冲波纹", rippleColor: "#FACC15" },
  },
  sakura: {
    leftClick: {
      textStyle: "中文数字 (一, 二, 三)", textColor: "#BE185D", fontSize: 20, textEasing: "弹跳",
      particleStyle: "心形", particlePalette: ["#FDA4AF","#F9A8D4","#FBCFE8","#FCE7F3","#FDF2F8"],
      particleCount: 28, particleSpread: 78, particleGravity: 20, particleWind: 5, particleBounce: 12,
      particleSize: 14, particleOpacity: 90, particleColorMode: "随机轻变化",
      rippleStyle: "柔和面波", rippleSize: 58, rippleOpacity: 42, rippleColor: "#F9A8D4",
      textFontFamily: "楷体", sound: false, shake: 18, textShadow: "柔和",
    },
    doubleClick: {
      textStyle: "中文数字 (一, 二, 三)", textColor: "#BE185D", fontSize: 22, textEasing: "弹性",
      particleStyle: "心形", particlePalette: ["#FDA4AF","#F9A8D4","#FBCFE8","#FCE7F3","#FDF2F8"],
      particleCount: 36, particleSpread: 86, particleGravity: 24, particleWind: 8, particleBounce: 18,
      particleSize: 16, particleOpacity: 92, particleColorMode: "随机轻变化",
      rippleStyle: "回声环", rippleSize: 68, rippleOpacity: 52, rippleColor: "#F9A8D4",
      textFontFamily: "楷体", sound: false, shake: 28, textShadow: "柔和",
    },
    wheel: { particleStyle: "心形", particle: true, particleCount: 14, particleSpread: 44, particleGravity: 28, particleColorMode: "随机轻变化", particlePalette: ["#FDA4AF","#F9A8D4","#FBCFE8"], ripple: true, rippleColor: "#F9A8D4", textColor: "#BE185D", sound: false },
    hover: { ripple: true, rippleStyle: "柔和面波", rippleColor: "#F9A8D4", rippleOpacity: 34, cursorOverride: "切换到 pointer", textEnabled: true, textKind: "文本飘字", textTags: ["🌸", "🍃", "🌺"], textTagPlayMode: "随机显示", textColor: "#BE185D", fontSize: 16, textFontFamily: "楷体", sound: false },
    rightClick: { particle: true, particleStyle: "心形", particleGravity: 16, particlePalette: ["#FDA4AF","#F9A8D4"], particleColorMode: "随机轻变化", rippleColor: "#F9A8D4", sound: false },
    longPress: { particle: true, particleStyle: "心形", particleGravity: 30, particlePalette: ["#FDA4AF","#F9A8D4","#FBCFE8"], rippleColor: "#F9A8D4", sound: false, textFontFamily: "楷体" },
  },
};

export function getDefaultActionConfigs(themeId) {
  const themeOverrides = THEME_ACTION_OVERRIDES[themeId] || {};
  return Object.fromEntries(
    Object.entries(ACTION_CONFIG_PRESETS).map(([actionId, config]) => [
      actionId,
      {
        ...cloneActionConfig(config),
        ...(themeOverrides[actionId] || {}),
      },
    ])
  );
}

export function getTimingFieldMeta(actionId) {
  if (actionId === "longPress") {
    return { label: "长按阈值", hint: "按住多久以后才算长按。", min: 200, max: 900 };
  }
  if (actionId === "doubleClick") {
    return { label: "双击间隔", hint: "两次点击之间允许的最大间隔。", min: 180, max: 520 };
  }
  if (actionId === "hover") {
    return { label: "停留阈值", hint: "鼠标停多久之后再触发 hover 效果。", min: 80, max: 700 };
  }
  if (actionId === "wheel") {
    return { label: "合并间隔", hint: "连续滚动时，多久合并为一次反馈。", min: 80, max: 520 };
  }
  return { label: "触发延迟", hint: "动作识别后，延迟多久开始反馈。", min: 0, max: 320 };
}

export function getConflictsForAction(actionId, actionConfigs) {
  const current = actionConfigs[actionId];
  const conflicts = [];

  if (actionId === "longPress" && current.sound && actionConfigs.leftClick.sound) {
    conflicts.push("长按和左键单击都在使用音效，后续需要明确谁先触发。");
  }

  if (!current.textEnabled && !current.particle && !current.ripple && !current.sound && !current.animationEnabled && !current.imageEnabled) {
    conflicts.push("当前动作没有绑定任何反馈，用户点击时会感觉没效果。");
  }

  return conflicts;
}
